# Problem Statement - Implement Union, Intersection, Complement and Difference operations on fuzzy sets. Also create fuzzy relations by Cartesian product of any two fuzzy sets and perform max-min composition on any two fuzzy relations.

In [5]:
import numpy as np

In [8]:
# Elements: a, b, c, d
A = np.array([0.2, 0.7, 0.5, 0.0])
B = np.array([0.6, 0.4, 0.0, 0.8])

In [3]:
def fuzzy_union(A, B):
    return np.maximum(A, B)
print("Union:", fuzzy_union(A, B))


Union: [0.6 0.7 0.5 0.8]


In [4]:
#For each element, picks the minimum value.

def fuzzy_intersection(A, B):
    return np.minimum(A, B)
print("Intersection:", fuzzy_intersection(A, B))




Intersection: [0.2 0.4 0.  0. ]


In [6]:
#For each element, take the minimum of A(x) and 1 - B(x).
##Think: "What part of A remains if we remove B?"
def fuzzy_complement(A):
    return 1 - A
print("Complement of A:", fuzzy_complement(A))


Complement of A: [0.8 0.3 0.5 1. ]


In [9]:
def fuzzy_difference(A, B):
    return np.minimum(A, 1 - B)
print("Difference (A - B):", fuzzy_difference(A, B))

Difference (A - B): [0.2 0.6 0.5 0. ]


In [10]:
##Outer product of A and B.
#Forms a matrix/grid: every element of A multiplies every element of B.


def cartesian_product(A, B):
    return np.minimum.outer(A, B)

R = cartesian_product(A, B)
S = cartesian_product(B, A)

print("Relation R:\n", R)
print("Relation S:\n", S)


Relation R:
 [[0.2 0.2 0.  0.2]
 [0.6 0.4 0.  0.7]
 [0.5 0.4 0.  0.5]
 [0.  0.  0.  0. ]]
Relation S:
 [[0.2 0.6 0.5 0. ]
 [0.2 0.4 0.4 0. ]
 [0.  0.  0.  0. ]
 [0.2 0.7 0.5 0. ]]


In [11]:
def max_min_composition(R, S):
    T = []
    for row in R:
        new_row = []
        for col in S.T:
            new_row.append(np.max(np.minimum(row, col)))
        T.append(new_row)
    return np.array(T)

T = max_min_composition(R, S)
print("Max-Min Composition:\n", T)

Max-Min Composition:
 [[0.2 0.2 0.2 0. ]
 [0.2 0.7 0.5 0. ]
 [0.2 0.5 0.5 0. ]
 [0.  0.  0.  0. ]]
